<a href="https://colab.research.google.com/github/dan-an/machine_learning/blob/master/pytorch/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [0]:
x = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [5]:
x.size()

torch.Size([3, 4])

In [6]:
x.shape

torch.Size([3, 4])

In [0]:
mask = x > 3

In [8]:
x[mask]

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
x = torch.rand(2000, 3000)
x

In [10]:
torch.cuda.is_available()

True

In [12]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [13]:
device = torch.device('cuda:0' if torch.cuda.is_available else 'cpu')
device

device(type='cuda', index=0)

In [0]:
x_cuda = x.to(device)

In [16]:
%time y = (x - x + x * 10) ** 2
y

CPU times: user 23.7 ms, sys: 33.5 ms, total: 57.2 ms
Wall time: 74.9 ms


tensor([[7.9834e-02, 1.6016e+00, 9.2487e+00,  ..., 4.1388e+00, 5.5217e-01,
         2.7221e+00],
        [3.4951e+01, 8.7025e+01, 1.1205e-01,  ..., 2.2351e+01, 2.8501e+00,
         7.2888e+01],
        [3.4207e+00, 1.9714e-01, 5.6540e+01,  ..., 9.1222e+01, 4.2173e+00,
         7.8288e+01],
        ...,
        [2.4632e+01, 2.5186e+00, 8.7019e+01,  ..., 1.4030e+01, 4.9757e+00,
         2.6203e+01],
        [1.4803e+01, 5.3953e+00, 4.2806e+01,  ..., 8.8848e+01, 8.9458e+01,
         4.8911e+01],
        [1.5283e+00, 3.1888e+01, 4.1685e+01,  ..., 2.9620e-02, 4.2900e+01,
         9.1200e+01]])

In [19]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10) ** 2
y_cuda

CPU times: user 2.71 ms, sys: 0 ns, total: 2.71 ms
Wall time: 1.99 ms


tensor([[7.9834e-02, 1.6016e+00, 9.2487e+00,  ..., 4.1388e+00, 5.5217e-01,
         2.7221e+00],
        [3.4951e+01, 8.7025e+01, 1.1205e-01,  ..., 2.2351e+01, 2.8501e+00,
         7.2888e+01],
        [3.4207e+00, 1.9714e-01, 5.6540e+01,  ..., 9.1222e+01, 4.2173e+00,
         7.8288e+01],
        ...,
        [2.4632e+01, 2.5186e+00, 8.7019e+01,  ..., 1.4030e+01, 4.9757e+00,
         2.6203e+01],
        [1.4803e+01, 5.3953e+00, 4.2806e+01,  ..., 8.8848e+01, 8.9458e+01,
         4.8911e+01],
        [1.5283e+00, 3.1888e+01, 4.1685e+01,  ..., 2.9620e-02, 4.2900e+01,
         9.1200e+01]], device='cuda:0')